title = "Photos by Jack Allard"
languageCode = "en-us"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "America/Los_Angeles"
theme = ["github.com/nicokaiser/hugo-theme-gallery"]
timeout = 1000

[params]
  title = "My Gallery"
  description = "Example site for hugo-theme-gallery"
  defaultTheme = "dark"

[author]
  name = "Jack Allard"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[menu]
[[menu.footer]]
  name = "Source Code"
  url = "https://github.com/jackallard17/photo-blog"
  weight = 3
